import mongoose from 'mongoose';

const VehicleSchema = new mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId,
  vehicleType: String,
  brand: String,
  model: String,
  modelGeneration: String,
  modelCode: String,
  modelType: String,
  modelYear: String,
  version: String,
  engineManufacturer: String,
  engineModel: String,
  engineCode: String,
  fuel: String,
  emissionStandardEuro: String,
  emissionStandardTier: String,
  cm3: String,
  kW: String,
  ps: String,
  hp: String,
  nm: String,
  eCUType: String,
  ecuBrand: String,
  ecuMicroprocessor: String,
  ecuVersion: String,
  kESSv2YesNo: String,
  kESSv2Protocol: String,
  ktagYesNo: String,
  kTAGGroup: String,
  kTAGProtocol: String,
  pWG3Protocol: String,
})

export default mongoose.model('Vehicle', VehicleSchema)
